version: '3.8'

services:
  # 1. Backend API
  backend:
    image: vydhal/edudocs-backend:latest
    environment:
      # Conecta ao Postgres usando o nome do serviço na rede interna
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@edudocs_db:5432/${POSTGRES_DB}?schema=public
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
    depends_on:
      - edudocs_db
    volumes:
      - edudocs_uploads:/app/uploads
    networks:
      - SimpliSoft # Para falar com o Traefik
      - interna_network_docs # Para falar com o Postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        # Define a rede que o Traefik deve usar para alcançar este container
        - "traefik.docker.network=SimpliSoft"
        # Rota para API e Uploads (Mesmo domínio, filtrando por Path)
        - "traefik.http.routers.edudocs-backend.rule=Host(`edudocs.simplisoft.com.br`) && (PathPrefix(`/api`) || PathPrefix(`/uploads`))"
        - "traefik.http.routers.edudocs-backend.entrypoints=websecure"
        - "traefik.http.routers.edudocs-backend.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.edudocs-backend.loadbalancer.server.port=3001"

  # 2. Frontend
  frontend:
    image: vydhal/edudocs-frontend:latest
    environment:
      - VITE_API_URL=https://edudocs.simplisoft.com.br/api
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=SimpliSoft"
        # Rota Raiz (Frontend)
        - "traefik.http.routers.edudocs-frontend.rule=Host(`edudocs.simplisoft.com.br`)"
        - "traefik.http.routers.edudocs-frontend.entrypoints=websecure"
        - "traefik.http.routers.edudocs-frontend.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.edudocs-frontend.loadbalancer.server.port=80"
    networks:
      - SimpliSoft

  # 3. Banco de Dados
  edudocs_db:
    image: postgres:15-alpine
    deploy:
      replicas: 1
      placement:
        constraints: [ node.role == manager ] # Recomendado para persistência
      restart_policy:
        condition: on-failure
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_v5:/var/lib/postgresql/data
    networks:
      - interna_network_docs
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_v5:
  edudocs_uploads:


networks:
  # Rede pública existente no Swarm (onde o Traefik está)
  SimpliSoft:
    external: true
  # Rede interna para comunicação Backend <-> DB
  interna_network_docs:
    driver: overlay
    attachable: true
